### ISSUE TITLE
"Failed to load key...."

### ISSUE THREAD

**Issue by smblott-github** [google/chrome-ssh-agent#28] opened 2022-08-12 14:07 UTC
Starting this afternoon, I'm seeing this error message:

![image](https://user-images.githubusercontent.com/2641335/184370352-07fa34f6-7d3a-49b7-9146-f15a8161227d.png)

`failed to load key: failed to decrypt key: key marshalling failed: x509: unknown key type while marshaling PKCS#8: *ed25519.PrivateKey*`

I think there's a new version out, right?  Something seems broken.

Edit: to clarify, I see this message when I try to load an existing key (which was loaded and worked this morning!).

Thanks.

**Comment by ralimi** [comment] 2022-08-13 04:43
Thank you for the report here. 

It looks like the issue is a combination of 2 things:
1. A unexpected inconsistency between return types in the Go libraries.  In particular, https://github.com/golang/go/blob/2f6783c098696790223eae6986700868e9da0472/src/crypto/x509/pkcs8.go#L121 shows that `x509.MarshalPKCS8PrivateKey()` expects a non-pointer value when referring to ed25519 keys (yet it expects a pointer for all the rest).    However, `ssh.ParseRawPrivateKey()` consistently returns a pointer type (see https://github.com/golang/crypto/blob/630584e8d5aaa1472863b49679b2d5548d80dcba/ssh/keys.go#L1361).   Interestingly, `ssh.NewPublicKey()` assumes it would not be a pointer (see https://github.com/golang/crypto/blob/630584e8d5aaa1472863b49679b2d5548d80dcba/ssh/keys.go#L1036).
2. Our tests were using Go's `t.Parallel()` to run multiple tests in parallel, which apparently caused them to silently pass.  I strongly suspect this is unique to something about running them under WebAssembly.  There was a test using OpenSSH keys that would have caught this, but it was incorrectly passing.

I have a reproducible test case now, and am working on a fix and a new release.

**Comment by ralimi** [comment] 2022-08-13 05:34
Version 0.0.22 has been pushed to the Chrome Webstore, and is pending review.

**Comment by ralimi** [comment] 2022-08-15 14:44
To avoid duplicate issues, I'll reopen this while it is pending release in the webstore.

**Comment by cshelton1409** [comment] 2022-08-16 13:02
The review of version 0.0.22 seems to be complete, since I updated my extensions earlier today, and received this new version.  The issue with loading ed25519 keys is fixed in this version, with my key working again for ssh authentication.

**Comment by ralimi** [comment] 2022-08-17 02:13
@cshelton1409 excellent - thanks for confirming!

**Closed by ralimi** 2022-08-17 02:13 UTC
